:sprinkles:
- :location: app/assets/images/sprinkles/doge.png
  :rate: 100
  :min: 1
  :max: 3
- :location: app/assets/images/sprinkles/doge-left.png
  :rate: 75
  :min: 1
  :max: 3
- :location: app/assets/images/sprinkles/trollface.png
  :rate: 33
  :min: 1
  :max: 1
- :location: app/assets/images/sprinkles/grumpycat.png
  :rate: 33
  :min: 1
  :max: 1
- :location: app/assets/images/sprinkles/cblogo.png
  :rate: 100
  :min: 1
  :max: 1
- :location: app/assets/images/sprinkles/castle.png
  :rate: 33
  :min: 1
  :max: 1
- :location: app/assets/images/sprinkles/ironman.png
  :rate: 33
  :min: 1
  :max: 1